"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 21:28:24.258452
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import receptionist.db.base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=32), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("config_hash", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("state_json", sa.JSON(), nullable=False),
        sa.Column("started_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("ended_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "real_started_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("clock_source", sa.String(length=8), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("after_hours", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("urgency", sa.String(length=16), nullable=True),
        sa.Column("caller_name", sa.String(length=200), nullable=True),
        sa.Column("caller_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("caller_email", sa.String(length=320), nullable=True),
        sa.Column("service_address", sa.String(length=500), nullable=True),
        sa.Column("recording_url", sa.Text(), nullable=True),
        sa.Column("public_log_url", sa.Text(), nullable=True),
        sa.Column("disconnection_reason", sa.String(length=64), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("llm_cost_usd", sa.Float(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_conversations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "tenant_id",
            "channel",
            "external_id",
            name=op.f("uq_conversations_tenant_id_channel_external_id"),
        ),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversations_tenant_outcome", ["tenant_id", "outcome"], unique=False
        )
        batch_op.create_index(
            "ix_conversations_tenant_started", ["tenant_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "ix_conversations_tenant_urgency", ["tenant_id", "urgency"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("locked_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_jobs_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_jobs_dedupe_key")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_status_run_after", ["status", "run_after"], unique=False)

    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("received_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("processed_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_webhook_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint(
            "provider",
            "event_type",
            "external_id",
            name=op.f("uq_webhook_events_provider_event_type_external_id"),
        ),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_alerts_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_alerts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_alerts_dedupe_key")),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("active_guard", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_booking_uid", sa.String(length=128), nullable=True),
        sa.Column("provider_booking_id", sa.String(length=64), nullable=True),
        sa.Column("event_type_id", sa.String(length=64), nullable=True),
        sa.Column("start_utc", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("end_utc", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("attendee_name", sa.String(length=200), nullable=False),
        sa.Column("attendee_phone_e164", sa.String(length=20), nullable=False),
        sa.Column("attendee_email", sa.String(length=320), nullable=True),
        sa.Column("attendee_email_is_placeholder", sa.Boolean(), nullable=False),
        sa.Column("service_address", sa.String(length=500), nullable=False),
        sa.Column("raw_request_json", sa.JSON(), nullable=True),
        sa.Column("raw_response_json", sa.JSON(), nullable=True),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_bookings_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_bookings_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("active_guard", name=op.f("uq_bookings_active_guard")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_bookings_idempotency_key")),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.create_index("ix_bookings_tenant_start", ["tenant_id", "start_utc"], unique=False)

    op.create_table(
        "callback_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("preferred_window", sa.String(length=200), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("phone_confirmed", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_callback_requests_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_callback_requests_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_callback_requests")),
    )
    with op.batch_alter_table("callback_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_callback_requests_tenant_status", ["tenant_id", "status"], unique=False
        )

    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("interest", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_leads_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_leads_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index("ix_leads_tenant_created", ["tenant_id", "created_at"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("interrupted", sa.Boolean(), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_messages_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "seq", name=op.f("uq_messages_conversation_id_seq")),
    )
    op.create_table(
        "outbound_emails",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("to_hash", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_outbound_emails_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_outbound_emails_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_emails")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_outbound_emails_dedupe_key")),
    )
    op.create_table(
        "summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_summaries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_summaries_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summaries")),
        sa.UniqueConstraint("conversation_id", name=op.f("uq_summaries_conversation_id")),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("args_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_tool_calls_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tool_calls_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tool_calls_conversation_created", ["conversation_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_tool_calls_tenant_tool_created",
            ["tenant_id", "tool_name", "created_at"],
            unique=False,
        )

    op.create_table(
        "turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("channel_response_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("t_received", receptionist.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("first_audible_ms", sa.Integer(), nullable=True),
        sa.Column("answer_first_chunk_ms", sa.Integer(), nullable=True),
        sa.Column("answer_done_ms", sa.Integer(), nullable=True),
        sa.Column("filler_used", sa.Boolean(), nullable=False),
        sa.Column("tool_wait_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("guard_triggers", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_turns_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_turns_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(
            "ix_turns_conversation_index", ["conversation_id", "turn_index"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index("ix_turns_conversation_index")

    op.drop_table("turns")
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_tool_calls_tenant_tool_created")
        batch_op.drop_index("ix_tool_calls_conversation_created")

    op.drop_table("tool_calls")
    op.drop_table("summaries")
    op.drop_table("outbound_emails")
    op.drop_table("messages")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index("ix_leads_tenant_created")

    op.drop_table("leads")
    with op.batch_alter_table("callback_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_callback_requests_tenant_status")

    op.drop_table("callback_requests")
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_index("ix_bookings_tenant_start")

    op.drop_table("bookings")
    op.drop_table("alerts")
    op.drop_table("webhook_events")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_run_after")

    op.drop_table("jobs")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_conversations_tenant_urgency")
        batch_op.drop_index("ix_conversations_tenant_started")
        batch_op.drop_index("ix_conversations_tenant_outcome")

    op.drop_table("conversations")
    op.drop_table("tenants")
    # ### end Alembic commands ###
